class Borey
  def self.all
    ['999',
     'Angkor Phnom Penh',
     'Ataingmeas',
     'B.S Holiday Villa',
     'Camko City',
     'Canadia',
     'Chamkamorn',
     'Chey Ordom',
     'Di Dok',
     'Dream Town',
     'Ekareach',
     'Elite Town',
     'Garden Tangov',
     'Grand Phnom Penh',
     'Happiness City',
     'Hi Tech',
     'Hillton Park Villa',
     'KL',
     'Kang Meng',
     'Keang Hort',
     'Koh Pich',
     'Laor Vichet',
     'Lim Chheang Hor',
     'Lim Chhieng Hak',
     'Meng Ly',
     'Moha Sethey',
     'Mongkul Phnom Penh',
     'Monorom',
     'Nagara',
     'New World',
     'Northbridge',
     'Orkide Villa',
     'Peng Hout',
     'Phnom Penh Thmey',
     'Pich',
     'Premprey',
     'Prince Town',
     'Rever Town',
     'Rith',
     'Santepheap',
     'Sen Monorom',
     'Sen Sok Town',
     'Sok San',
     'Sony',
     'Star City',
     'Sun Wah',
     'Sunway',
     'Thai Chun Kry',
     'Tonle Bassac Garden',
     'Toul Sangke',
     'Tropicana',
     'Varina',
     'Villa Sen Monorom Phnom Penh Meas',
     'Vimean Phnom Penh']
  end
end